language: python
notifications:
  email: false
python:
    - "2.5"
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
# command to install dependencies
install: "python setup.py install"
# command to run tests
script: "python -m unittest ConcordanceCrawler.tests"
