language: python
notifications:
  email: false
python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
# command to install dependencies
install: 
    - python setup.py install
# command to run tests
script: 
    - ConcordanceCrawler -h
    - python -m unittest ConcordanceCrawler.tests
    - ConcordanceCrawler a -v 0 -n 1
		- ConcordanceCrawler a -v 0 -n 1 -o xml
		- pip install textblob
