'''Thresholds for EngDetector. Generated by eng_englishness.py,
(by function gen_threshold), can be changed manually. 

Threshold for "englishness" will be chosen by lenght of input text, because
the longer text, the better it fits to the vectors of frequencies of 1,2,3-grams in whole
English Wikipedia.

In comments are means similarities to English-Wikipedia vector of some
English and Non-English samples with given length.
'''


thresholds = {
10: 0.371144073594, # nengmean: 0.354083889648 engmean: 0.388204257539 
20: 0.460171986716, # nengmean: 0.432574982111 engmean: 0.48776899132 
30: 0.511007842706, # nengmean: 0.470337984236 engmean: 0.551677701176 
40: 0.5488607745, # nengmean: 0.502323065857 engmean: 0.595398483144 
50: 0.577975661938, # nengmean: 0.529324700059 engmean: 0.626626623817 
60: 0.597429829037, # nengmean: 0.545898152308 engmean: 0.648961505767 
70: 0.613048750475, # nengmean: 0.558150708464 engmean: 0.667946792486 
80: 0.628956423525, # nengmean: 0.569474303958 engmean: 0.688438543093 
90: 0.639966603934, # nengmean: 0.577406806219 engmean: 0.70252640165 
100: 0.651404243543, # nengmean: 0.588456850278 engmean: 0.714351636808 
150: 0.693652663185, # nengmean: 0.62318492013 engmean: 0.764120406239 
200: 0.720237531774, # nengmean: 0.646159064923 engmean: 0.794315998626 
300: 0.750353115672, # nengmean: 0.67234060948 engmean: 0.828365621864 
400: 0.769829721622, # nengmean: 0.690155290123 engmean: 0.849504153121 
500: 0.780011413325, # nengmean: 0.700626803978 engmean: 0.859396022672 
1000: 0.816707234867, # nengmean: 0.732428252494 engmean: 0.900986217239 
1500: 0.81886588301, # nengmean: 0.744988231283 engmean: 0.892743534736 
2000: 0.839629721165, # nengmean: 0.754706292292 engmean: 0.924553150038 
5000: 0.859149132835, # nengmean: 0.775749916422 engmean: 0.942548349247 
}
# Thresholds were generated correctly.
