from ConcordanceCrawler.tests.visitor_tests import TestVisitor
from ConcordanceCrawler.tests.formatter_tests import TestFormatter
from ConcordanceCrawler.tests.links_tests import TestLinks
from ConcordanceCrawler.tests.crawler_tests import TestCrawler
